### PR TITLE
Use SHLIB_EXT

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jakirkham** [comment]
Needs a re-render. Probably can just rebase on PR ( https://github.com/conda-forge/gdcm-feedstock/pull/1 ).

**Comment by Korijn** [comment]
AppVeyor seems to require a restart:

```
Build started
git clone -q https://github.com/conda-forge/gdcm-feedstock.git C:\projects\gdcm-feedstock
fatal: unable to access 'https://github.com/conda-forge/gdcm-feedstock.git/': Failed to connect to github.com port 443: Timed out
Command exited with code 128
```

Is it correct that I don't have the rights to do so?

**Comment by jschueller** [comment]
I think this can be merged, circleci succeded and one appveyor job has just a timeout.

**Comment by Korijn** [comment]
I trust your judgement!

**Pull request merged**
